services:
  embedding-service:
    build: ./embedding-service
    restart: always
    container_name: embedding-service
    expose:
      - 8000
    volumes:
      - ./logs:/app/logs
    env_file:
      - "global_config.env"
      - "secret_config.env"
  
  main-service:
    build: ./main-service
    restart: always
    container_name: main-service
    ports:
      - 8002:8000
    volumes:
      - ./logs:/app/logs
      - ./data_persistent:/data/persistent:ro
      - ./data_upload:/data/upload:rw
    env_file:
      - "global_config.env"
      - "secret_config.env"

  file-discovery-service:
    build: ./file-discovery-service
    restart: always
    container_name: file-discovery-service
    expose:
      - 8000
    volumes:
      - ./logs:/app/logs
      - ./data:/data:ro
    env_file:
      - global_config.env

  qdrant:
    image: qdrant/qdrant:v1.16.3
    restart: always
    container_name: qdrant
    volumes:
      - ./qdrant_data:/qdrant/storage
    expose:
      - 6333

  redis:
    image: redis:8.4.0
    restart: always
    container_name: redis
    volumes:
      - ./redis_cache:/data
    expose:
      - 6379
